name: Allure Integration

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress run with Cucumber
        uses: cypress-io/github-action@v4.2.0
        with:
          command: npm run cypress:execution-allure

      - name: Verificar si allure-results se ha generado
        run: |
          if [ -d "./allure-results" ]; then
            echo "Directorio allure-results existe."
          else
            echo "Directorio allure-results no existe."
            exit 1
          fi

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: allure
          path: allure

      - name: Crear directorio allure-results/history
        run: mkdir -p allure-results/history

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@1.9
        if: always()
        with:
          allure_results: allure-results
          gh_pages: allure

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: allure
          publish_dir: allure-history
